'use client';

/**
 * Chart Preferences Settings Component
 *
 * Allows users to configure chart styling preferences using Plotly templates.
 * Preferences apply to all charts generated by the VisualizationAgent.
 */

import { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  getChartPreferences,
  updateChartPreferences,
  createBuiltinTemplateConfig,
} from '@/services/chartPreferences.service';
import type {
  UserChartPreferences,
  ChartTemplateConfig,
  SavedTemplate,
} from '@/types/chartPreferences.types';
import { BuiltinTemplateSelector } from '@/components/settings/BuiltinTemplateSelector';
import { CustomTemplateCreator } from '@/components/settings/CustomTemplateCreator';
import { SavedTemplatesGrid } from '@/components/settings/SavedTemplatesGrid';
import { TemplatePreview } from '@/components/settings/TemplatePreview';

export function ChartPreferencesSettings() {
  const [preferences, setPreferences] = useState<UserChartPreferences | null>(null);
  const [selectedTemplate, setSelectedTemplate] = useState<ChartTemplateConfig | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [editingTemplate, setEditingTemplate] = useState<SavedTemplate | null>(null);
  const [activeTab, setActiveTab] = useState('builtin');

  // Load preferences on mount
  useEffect(() => {
    loadPreferences();
  }, []);

  const loadPreferences = async () => {
    console.log('[Frontend] Loading chart preferences...');
    try {
      setIsLoading(true);
      const prefs = await getChartPreferences();
      console.log('[Frontend] Loaded preferences:', prefs);
      console.log('[Frontend] chart_template:', prefs.chart_template);
      setPreferences(prefs);
      setSelectedTemplate(prefs.chart_template);
    } catch (error) {
      console.error('[Frontend] Failed to load chart preferences:', error);
      toast.error('Failed to load chart preferences');
    } finally {
      setIsLoading(false);
    }
  };

  const handleSelectBuiltinTemplate = (templateName: string) => {
    const newTemplate = createBuiltinTemplateConfig(templateName);
    setSelectedTemplate(newTemplate);
  };

  const handleSavePreferences = async () => {
    if (!selectedTemplate) {
      toast.error('No template selected');
      return;
    }

    console.log('[Frontend] Saving template:', selectedTemplate);

    try {
      setIsSaving(true);
      const updatedPrefs = await updateChartPreferences(selectedTemplate);
      console.log('[Frontend] Saved successfully, received:', updatedPrefs);
      setPreferences(updatedPrefs);
      toast.success('Chart preferences saved successfully');
    } catch (error) {
      console.error('[Frontend] Failed to save preferences:', error);
      toast.error('Failed to save preferences');
    } finally {
      setIsSaving(false);
    }
  };

  const handleResetToDefault = () => {
    const defaultTemplate = createBuiltinTemplateConfig('plotly_white');
    setSelectedTemplate(defaultTemplate);
  };

  const handleEditTemplate = (template: SavedTemplate) => {
    setEditingTemplate(template);
    setActiveTab('custom');
  };

  const handleEditComplete = () => {
    setEditingTemplate(null);
    loadPreferences();
  };

  if (isLoading) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <div className="text-center">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-500 border-t-transparent mx-auto mb-4"></div>
          <p className="text-gray-600">Loading chart preferences...</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">
          Chart Style Preferences
        </h2>
        <p className="text-gray-600">
          Configure how your charts look. These settings apply to all charts generated by queries.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Template Selection (2/3 width on large screens) */}
        <div className="lg:col-span-2 space-y-6">
          <Card className="p-6">
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="builtin">Built-in Templates</TabsTrigger>
                <TabsTrigger value="custom">Custom Creator</TabsTrigger>
                <TabsTrigger value="saved">My Templates</TabsTrigger>
              </TabsList>

              {/* Built-in Templates Tab */}
              <TabsContent value="builtin" className="mt-6">
                <BuiltinTemplateSelector
                  availableTemplates={preferences?.available_builtin_templates || []}
                  selectedTemplate={
                    selectedTemplate?.type === 'builtin' ? selectedTemplate.name : undefined
                  }
                  onSelectTemplate={handleSelectBuiltinTemplate}
                />
              </TabsContent>

              {/* Custom Template Creator Tab */}
              <TabsContent value="custom" className="mt-6">
                <CustomTemplateCreator
                  onTemplateCreated={(template) => setSelectedTemplate(template)}
                  editingTemplate={editingTemplate}
                  onEditComplete={handleEditComplete}
                />
              </TabsContent>

              {/* Saved Templates Tab */}
              <TabsContent value="saved" className="mt-6">
                <SavedTemplatesGrid
                  savedTemplates={preferences?.saved_templates || []}
                  onSelectTemplate={(template) => setSelectedTemplate(template)}
                  onRefresh={loadPreferences}
                  onEdit={handleEditTemplate}
                />
              </TabsContent>
            </Tabs>
          </Card>

          {/* Action Buttons */}
          <Card className="p-4">
            <div className="flex items-center justify-between">
              <Button
                variant="outline"
                onClick={handleResetToDefault}
                disabled={isSaving}
              >
                Reset to Default
              </Button>
              <Button
                onClick={handleSavePreferences}
                disabled={!selectedTemplate || isSaving}
                className="bg-blue-600 hover:bg-blue-700"
              >
                {isSaving ? 'Saving...' : 'Save Active Template'}
              </Button>
            </div>
          </Card>
        </div>

        {/* Right: Live Preview (1/3 width on large screens) */}
        <div className="lg:col-span-1">
          <Card className="p-6 sticky top-6">
            <h3 className="text-lg font-semibold mb-4">Live Preview</h3>
            <TemplatePreview template={selectedTemplate} />
          </Card>
        </div>
      </div>
    </div>
  );
}
